[package]
name = "ngram-indexer"
version = "0.1.0"
authors = ["Stu Black <trurl@freeshell.org>"]
build = "build.rs"

[dependencies]
flate2 = "0.2.*"
clap = "2.10.*"
csv = "0.14.*"
rustc-serialize = "0.3.*"
capnp = "0.7.*"

[build-dependencies]
capnpc = "0.7.*"